version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=myapi
      - DB_USERNAME=postgres
      - DB_PASSWORD=1908
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: mydb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1908
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
